"""Auto-tuning module for ModelPerf parallel strategy recommendation."""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional, Tuple

from modelperf.capture.graph import ComputationalGraph
from modelperf.analysis.what_if import WhatIfAnalyzer, WhatIfConfig
from modelperf.simulation.execution_result import ExecutionResult


class ParallelStrategyPreset(Enum):
    """Preset optimization objectives for parallel strategy tuning."""

    THROUGHPUT = "throughput"
    MEMORY_EFFICIENT = "memory_efficient"
    BALANCED = "balanced"


@dataclass
class TuningReport:
    """Report generated by auto-tuning search.

    Attributes:
        recommended_config: The top-ranked configuration dict.
        expected_iteration_time_ms: Predicted iteration time for the recommended config.
        expected_peak_memory_mb: Predicted peak memory for the recommended config.
        expected_throughput: Predicted throughput (tokens/sec) for the recommended config.
        all_results: All valid (config, result) tuples sorted by the chosen preset.
        pareto_frontier: Non-dominated configs on the throughput-vs-memory frontier.
    """

    recommended_config: Dict[str, Any] = field(default_factory=dict)
    expected_iteration_time_ms: float = 0.0
    expected_peak_memory_mb: float = 0.0
    expected_throughput: float = 0.0
    all_results: List[Tuple[Dict[str, Any], ExecutionResult]] = field(
        default_factory=list
    )
    pareto_frontier: List[Tuple[Dict[str, Any], ExecutionResult]] = field(
        default_factory=list
    )


class AutoTuner:
    """Automatic parallel strategy tuner using WhatIfAnalyzer simulation.

    Args:
        graph: A captured ComputationalGraph to tune against.
    """

    def __init__(self, graph: ComputationalGraph) -> None:
        self.graph = graph
        self.analyzer = WhatIfAnalyzer(graph)
        self.base_config = WhatIfConfig.from_graph(graph)

    def _infer_world_size(self) -> int:
        """Infer total world size from graph strategy / system config."""
        sc = self.graph.strategy_config
        sysc = self.graph.system_config

        if "world_size" in sysc:
            return int(sysc["world_size"])

        current_tp = sc.get("tensor_parallel_size", 1)
        current_pp = sc.get("pipeline_parallel_size", 1)
        current_dp = sc.get("data_parallel_size", 1)
        current_cp = sc.get("context_parallel_size", 1)

        return current_tp * current_pp * current_dp * current_cp

    @staticmethod
    def _get_tp_candidates(world_size: int, hidden_size: int, num_heads: int) -> List[int]:
        """Return valid TP sizes that divide world_size, hidden_size, and num_heads."""
        candidates: List[int] = []
        for tp in (1, 2, 4, 8):
            if tp > world_size:
                continue
            if world_size % tp != 0:
                continue
            if hidden_size % tp != 0:
                continue
            if num_heads % tp != 0:
                continue
            candidates.append(tp)
        return candidates if candidates else [1]

    @staticmethod
    def _get_pp_candidates(remaining_size: int, num_layers: int) -> List[int]:
        """Return valid PP sizes that divide remaining_size and num_layers."""
        candidates: List[int] = []
        for pp in (1, 2, 4, 8, 16, 32):
            if pp > remaining_size:
                continue
            if remaining_size % pp != 0:
                continue
            if num_layers % pp != 0:
                continue
            candidates.append(pp)
        return candidates if candidates else [1]

    def generate_search_space(
        self,
        world_size: Optional[int] = None,
        tp_values: Optional[List[int]] = None,
        pp_values: Optional[List[int]] = None,
        bs_values: Optional[List[int]] = None,
    ) -> Dict[str, List[Any]]:
        """Generate sensible search space based on model size and cluster size.

        The generated space covers tensor-parallel, pipeline-parallel, data-parallel,
        and micro-batch-size dimensions.  Invalid combinations (e.g. TP that does
        not divide hidden_size) are omitted at the candidate level, but the
        caller should still filter that ``TP * PP * DP == world_size`` because
        ``grid_search`` evaluates the Cartesian product.

        Args:
            world_size: Total number of GPUs.  Inferred from the graph when *None*.
            tp_values: Override list of TP candidates.
            pp_values: Override list of PP candidates.
            bs_values: Override list of micro-batch-size candidates.

        Returns:
            Parameter grid dict suitable for ``WhatIfAnalyzer.grid_search``.
        """
        if world_size is None:
            world_size = self._infer_world_size()

        hidden_size = self.base_config.hidden_size
        num_layers = self.base_config.num_layers
        num_heads = self.base_config.num_attention_heads

        if tp_values is None:
            tp_values = self._get_tp_candidates(world_size, hidden_size, num_heads)

        valid_configs: List[Tuple[int, int, int]] = []
        for tp in tp_values:
            if world_size % tp != 0:
                continue
            remaining = world_size // tp

            if pp_values is not None:
                pp_candidates = [p for p in pp_values if remaining % p == 0]
            else:
                pp_candidates = self._get_pp_candidates(remaining, num_layers)

            for pp in pp_candidates:
                dp = remaining // pp
                valid_configs.append((tp, pp, dp))

        tp_set = sorted({c[0] for c in valid_configs})
        pp_set = sorted({c[1] for c in valid_configs})
        dp_set = sorted({c[2] for c in valid_configs})

        if bs_values is None:
            bs_values = [1, 2, 4, 8]

        return {
            "tensor_parallel_size": tp_set,
            "pipeline_parallel_size": pp_set,
            "data_parallel_size": dp_set,
            "micro_batch_size": bs_values,
        }

    def _is_valid_config(
        self, changes: Dict[str, Any], expected_world_size: int
    ) -> bool:
        """Check that TP * PP * DP matches the expected world size."""
        tp = changes.get("tensor_parallel_size", 1)
        pp = changes.get("pipeline_parallel_size", 1)
        dp = changes.get("data_parallel_size", 1)
        return tp * pp * dp == expected_world_size

    def _extract_pareto_frontier(
        self,
        results: List[Tuple[Dict[str, Any], ExecutionResult]],
    ) -> List[Tuple[Dict[str, Any], ExecutionResult]]:
        """Extract Pareto frontier maximizing throughput and minimizing memory.

        A result is dominated if another result has **strictly** greater throughput
        **and** **less than or equal** memory (or vice-versa).
        """
        pareto: List[Tuple[Dict[str, Any], ExecutionResult]] = []

        for changes, result in results:
            dominated = False
            for _, other in results:
                if other is result:
                    continue

                better_throughput = (
                    other.throughput_tokens_per_sec > result.throughput_tokens_per_sec
                )
                better_memory = other.peak_memory_mb < result.peak_memory_mb
                equal_or_better_throughput = (
                    other.throughput_tokens_per_sec >= result.throughput_tokens_per_sec
                )
                equal_or_better_memory = (
                    other.peak_memory_mb <= result.peak_memory_mb
                )

                if (equal_or_better_throughput and equal_or_better_memory) and (
                    better_throughput or better_memory
                ):
                    dominated = True
                    break

            if not dominated:
                pareto.append((changes, result))

        pareto.sort(key=lambda x: x[1].throughput_tokens_per_sec, reverse=True)
        return pareto

    def search(
        self,
        gpu_memory_gb: float = 80.0,
        max_iteration_time_ms: Optional[float] = None,
        min_throughput: Optional[float] = None,
        preset: ParallelStrategyPreset = ParallelStrategyPreset.BALANCED,
        world_size: Optional[int] = None,
        param_grid: Optional[Dict[str, List[Any]]] = None,
        n_workers: Optional[int] = None,
    ) -> TuningReport:
        """Run grid search, filter by constraints, and return ranked recommendations.

        Args:
            gpu_memory_gb: Per-device memory budget in GiB.
            max_iteration_time_ms: Optional upper bound on iteration time (ms).
            min_throughput: Optional lower bound on throughput (tokens/sec).
            preset: Optimization objective.
            world_size: Total GPU count (inferred from graph when *None*).
            param_grid: Override search space ( skips ``generate_search_space`` ).
            n_workers: Thread-pool size for parallel simulation.

        Returns:
            A ``TuningReport`` containing the best config and full results.
        """
        expected_world_size = world_size or self._infer_world_size()
        search_space = param_grid or self.generate_search_space(
            world_size=expected_world_size
        )

        raw_results = self.analyzer.grid_search(
            search_space,
            sort_by="iteration_time_ms",
            ascending=True,
            n_workers=n_workers,
        )

        filtered_results: List[Tuple[Dict[str, Any], ExecutionResult]] = []
        for changes, result in raw_results:
            if not self._is_valid_config(changes, expected_world_size):
                continue

            config = self.analyzer.modify_config(changes)
            will_oom, _, _ = self.analyzer.predict_oom(config, gpu_memory_gb)
            if will_oom:
                continue

            if max_iteration_time_ms is not None:
                if result.iteration_time_ms > max_iteration_time_ms:
                    continue

            if min_throughput is not None:
                if result.throughput_tokens_per_sec < min_throughput:
                    continue

            filtered_results.append((changes, result))

        if not filtered_results:
            return TuningReport()

        if preset == ParallelStrategyPreset.THROUGHPUT:
            filtered_results.sort(
                key=lambda x: x[1].throughput_tokens_per_sec, reverse=True
            )
        elif preset == ParallelStrategyPreset.MEMORY_EFFICIENT:
            filtered_results.sort(key=lambda x: x[1].peak_memory_mb)
        elif preset == ParallelStrategyPreset.BALANCED:

            def _balanced_score(
                item: Tuple[Dict[str, Any], ExecutionResult],
            ) -> float:
                result = item[1]
                memory_factor = max(1.0, math.log(max(1.0, result.peak_memory_mb)))
                return result.throughput_tokens_per_sec / memory_factor

            filtered_results.sort(key=_balanced_score, reverse=True)

        pareto = self._extract_pareto_frontier(filtered_results)
        best_config, best_result = filtered_results[0]

        return TuningReport(
            recommended_config=best_config,
            expected_iteration_time_ms=best_result.iteration_time_ms,
            expected_peak_memory_mb=best_result.peak_memory_mb,
            expected_throughput=best_result.throughput_tokens_per_sec,
            all_results=filtered_results,
            pareto_frontier=pareto,
        )


def recommend(
    graph: ComputationalGraph,
    gpu_memory_gb: float = 80.0,
    max_iteration_time_ms: Optional[float] = None,
    min_throughput: Optional[float] = None,
    preset: ParallelStrategyPreset = ParallelStrategyPreset.BALANCED,
) -> TuningReport:
    """Convenience function for automatic parallel strategy recommendation.

    Creates an ``AutoTuner``, runs a full search with sensible defaults, and
    returns the resulting ``TuningReport``.

    Args:
        graph: Captured computational graph.
        gpu_memory_gb: Per-device memory budget in GiB (default: 80.0).
        max_iteration_time_ms: Optional upper bound on iteration time.
        min_throughput: Optional lower bound on throughput.
        preset: Optimization objective (default: ``BALANCED``).

    Returns:
        TuningReport with ranked recommendations.
    """
    tuner = AutoTuner(graph)
    return tuner.search(
        gpu_memory_gb=gpu_memory_gb,
        max_iteration_time_ms=max_iteration_time_ms,
        min_throughput=min_throughput,
        preset=preset,
    )
