import os
from typing import Dict, List
from ..capture.graph import ComputationalGraph, GraphNode, OpType


_TEST_FILE_TEMPLATE = '''"""
Auto-generated operator unit tests from computational graph.
Generated by ModelPerf OpTestGenerator.
"""

import pytest
import torch
from modelperf.testing.op_benchmark import OpBenchmark, OpAdapter

{test_cases}
'''

_CORRECTNESS_TEST_TEMPLATE = '''
def test_{sanitized_id}_correctness():
    """Correctness test for {op_type} ({node_id})."""
    adapter = OpAdapter()
    node = _build_node_{sanitized_id}()
    op_func, inputs_cpu = adapter.build(node)
    device = "cuda" if torch.cuda.is_available() else "cpu"
    inputs_gpu = [t.to(device) for t in inputs_cpu]
    if hasattr(op_func, "to"):
        op_func = op_func.to(device)
    benchmark = OpBenchmark(device=device, warmup=5, repeat=20)
    passed, error = benchmark._check_correctness(op_func, inputs_cpu, inputs_gpu)
    assert passed, f"Correctness failed for {node_id}: {{error}}"
'''

_PERFORMANCE_TEST_TEMPLATE = '''
def test_{sanitized_id}_performance():
    """Performance test for {op_type} ({node_id})."""
    adapter = OpAdapter()
    node = _build_node_{sanitized_id}()
    benchmark = OpBenchmark(device="cuda" if torch.cuda.is_available() else "cpu", warmup=10, repeat=100)
    result = benchmark.benchmark_node(node)
    print("[" + "{node_id}" + "] " + result.op_type + ": time=" + str(round(result.avg_time_ms, 3)) + "ms, "
          "FLOPs=" + str(result.flops) + ", FLOP/s=" + str(round(result.flops_utilization, 2)) + "TFLOP/s, "
          "mem_bw=" + str(round(result.memory_bandwidth_gbs, 2)) + "GB/s, "
          "peak_mem=" + str(round(result.peak_memory_mb, 2)) + "MB")
    assert result.avg_time_ms > 0, "Benchmark returned zero time"
    assert result.correctness_passed, "Correctness failed: " + str(result.correctness_error)
'''

_NODE_BUILDER_TEMPLATE = '''
def _build_node_{sanitized_id}():
    from modelperf.capture.graph import GraphNode, OpType
    node = GraphNode(
        node_id={node_id_repr},
        op_type={op_type_repr},
        node_type=OpType.{node_type},
        input_shapes={input_shapes_repr},
        output_shapes={output_shapes_repr},
        params={params_repr},
        tensor_dtype_size={dtype_size},
        hierarchy_path={hierarchy_path_repr},
        module_category={module_category_repr},
    )
    return node
'''


def _sanitize_id(node_id: str) -> str:
    return node_id.replace(".", "_").replace("-", "_").replace(":", "_")


class OpTestGenerator:
    def __init__(self, output_dir: str = "generated_tests"):
        self.output_dir = output_dir

    def generate_all(self, graph: ComputationalGraph):
        os.makedirs(self.output_dir, exist_ok=True)
        nodes_by_category: Dict[str, List[GraphNode]] = {}
        for node in graph.nodes.values():
            cat = node.module_category or "uncategorized"
            if node.node_type == OpType.COMMUNICATION:
                cat = "communication"
            elif node.node_type == OpType.OPTIMIZER:
                cat = "optimizer"
            nodes_by_category.setdefault(cat, []).append(node)

        for category, nodes in nodes_by_category.items():
            self._write_category_tests(category, nodes)

    def generate_for_node(self, node: GraphNode, output_path: str):
        content = self._build_test_content([node])
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(content)

    def _write_category_tests(self, category: str, nodes: List[GraphNode]):
        file_name = f"test_{category}.py"
        file_path = os.path.join(self.output_dir, file_name)
        content = self._build_test_content(nodes)
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(content)

    def _build_test_content(self, nodes: List[GraphNode]) -> str:
        builders: List[str] = []
        tests: List[str] = []
        for node in nodes:
            sid = _sanitize_id(node.node_id)
            builders.append(self._render_node_builder(node, sid))
            tests.append(self._render_correctness_test(node, sid))
            tests.append(self._render_performance_test(node, sid))

        test_cases = "\n".join(builders + tests)
        return _TEST_FILE_TEMPLATE.format(test_cases=test_cases)

    def _render_node_builder(self, node: GraphNode, sid: str) -> str:
        return _NODE_BUILDER_TEMPLATE.format(
            sanitized_id=sid,
            node_id_repr=repr(node.node_id),
            op_type_repr=repr(node.op_type),
            node_type=node.node_type.name,
            input_shapes_repr=repr(node.input_shapes),
            output_shapes_repr=repr(node.output_shapes),
            params_repr=repr(node.params),
            dtype_size=node.tensor_dtype_size,
            hierarchy_path_repr=repr(node.hierarchy_path),
            module_category_repr=repr(node.module_category),
        )

    def _render_correctness_test(self, node: GraphNode, sid: str) -> str:
        return _CORRECTNESS_TEST_TEMPLATE.format(
            sanitized_id=sid,
            op_type=node.op_type,
            node_id=node.node_id,
        )

    def _render_performance_test(self, node: GraphNode, sid: str) -> str:
        return _PERFORMANCE_TEST_TEMPLATE.format(
            sanitized_id=sid,
            op_type=node.op_type,
            node_id=node.node_id,
        )
